name: Back-end CI/CD

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: backend-deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=test-ci-cd -Dsonar.projectName='test-ci-cd'

      - name: Run Tests
        run: mvn test

      - name: Build Back-end
        run: mvn clean install

      - name: Build Docker image
        run: docker build -t bobapp-back .

      - name: Deploy Back-end
        run: docker run -p 8080:8080 --name bobapp-back -d bobapp-back

      - name: Collect and report code coverage
        run: mvn jacoco:report
