name: Back-end CI/CD

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: backend-deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build, analyze, and test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=BobApp-Back
          mvn test

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest .

      - name: Log in to Docker Hub and push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest

      - name: Deploy Back-end
        run: docker run -p 8080:8080 --name bobapp-back -d ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest

      - name: Collect and report code coverage
        run: mvn jacoco:report
