name: Front-end CI/CD

on:
  push:
    branches:
      - main

jobs:
  frontend:
    name: frontdeploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cwd: "front"

      - name: Install dependencies
        run: npm install

      - name: Build Front-end
        run: npm run build

      - name: Build Docker image
        run: docker build -t bobapp-front .

      - name: Deploy Front-end
        run: docker run -p 8080:8080 --name bobapp-front -d bobapp-front
